### PR TITLE
Comments on Tutorial 02

### PR DESCRIPTION
**Pull request by sou412**

### CODE REVIEW

**Comment by sou412** [comment]
Maybe I'm missing something here as I haven't checked the code carefully, but elements of `ages` change between two chunks. 

So, the question under `Complex relationals`, there's only one element that satisfies the condition (`19`), but in the next chunk somehow the second element gets replaced to `20` so the average becomes `19.5`.

Screen Shot 2020-08-31 at 19 56 52

**Comment by sou412** [comment]
> Maybe I'm missing something here as I haven't checked the code carefully, but elements of `ages` change between two chunks.
> 
> So, the question under `Complex relationals`, there's only one element that satisfies the condition (`19`), but in the next chunk somehow the second element gets replaced to `20` so the average becomes `19.5`.
> 
> Screen Shot 2020-08-31 at 19 56 52

I found that `ages` are generated twice in https://github.com/mattblackwell/qsslearnr/blob/ac817c1f045c9af62150aa4d336e4ef4c9d9adef/inst/tutorials/02-causality2/02-causality2.Rmd#L62
and 
https://github.com/mattblackwell/qsslearnr/blob/ac817c1f045c9af62150aa4d336e4ef4c9d9adef/inst/tutorials/02-causality2/02-causality2.Rmd#L97

**Comment by mattblackwell** [comment]
Yeah, let's make replace the first ages vector with the second. So both should have `ages[2] == 20`.

**Comment by sou412** [comment]
I also find that `Submit Answer` and `Solution` show up at the same time. Is this intentional, given that questions are somewhat complex? 

Example: 
https://github.com/mattblackwell/qsslearnr/blob/ac817c1f045c9af62150aa4d336e4ef4c9d9adef/inst/tutorials/02-causality2/02-causality2.Rmd#L174-L202

**Comment by mattblackwell** [comment]
We could add a hint which would display first, before the solution. You only get access to the solution once you click on the hint. Something like:

`````r
```{r factor-hint} 
 ## fill in the last line of code to create a character vector for the type of  
 ## application that was sent 
 resume$type <- NA 
 resume$type[resume$race == "black" & resume$sex == "female"] <- "BlackFemale" 
 resume$type[resume$race == "black" & resume$sex == "male"] <- "BlackMale" 
 resume$type[resume$race == "white" & resume$sex == "female"] <- "WhiteFemale" 
 resume$type[resume$race == ??? & resume$sex == ???] <-  "WhiteMale"
  
 ## turn the character vector into a factor 
 resume$type <-  as.factor(...)
 ``` 
`````

**Review by sou412 — COMMENTED** [review]
Add hints

**Pull request merged**
